name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SCCACHE_GHA_ENABLED: 'true'
  ANDROID_NDK_VERSION: r24
  ANDROID_TARGET_SDK_VERSION: 24

permissions:
  contents: read

jobs:
  build-android:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-22.04, target_arch: arm }
          - { os: ubuntu-22.04, target_arch: arm64 }
          - { os: ubuntu-22.04, target_arch: x86_64 }

    runs-on: ${{ matrix.config.os }}
    env:
      TARGET_ARCH: ${{ matrix.config.target_arch }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: Install build utils
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.ANDROID_NDK_VERSION }}
          add-to-path: false

      - name: Build
        env:
          MY_ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          ./tools/android_build.sh $MY_ANDROID_NDK_HOME $ANDROID_TARGET_SDK_VERSION $TARGET_ARCH
          rm -rf ./out_android/libnode

      - uses: actions/upload-artifact@v4
        with:
          name: node-android-${{ env.TARGET_ARCH }}
          path: out_android